FROM node:22

RUN corepack enable
RUN corepack prepare pnpm --activate

WORKDIR /app

COPY package*.json /app/

RUN pnpm install

RUN npx -y playwright install --with-deps

COPY ./ /app/

ARG VITE_API_URL=${VITE_API_URL}
