FROM node:22

WORKDIR /app

COPY package*.json /app/

RUN npm install

RUN npx -y playwright install --with-deps

COPY ./ /app/

ARG VITE_API_URL=${VITE_API_URL}
ARG VITE_PROJECT_NAME=${VITE_PROJECT_NAME}
