// This file is auto-generated by @hey-api/openapi-ts

import { type Options as ClientOptions, type TDataShape, type Client, urlSearchParamsBodySerializer } from '@hey-api/client-fetch';
import type { ItemsReadItemsData, ItemsReadItemsResponse, ItemsReadItemsError, ItemsCreateItemData, ItemsCreateItemResponse, ItemsCreateItemError, ItemsDeleteItemData, ItemsDeleteItemResponse, ItemsDeleteItemError, ItemsReadItemData, ItemsReadItemResponse, ItemsReadItemError, ItemsUpdateItemData, ItemsUpdateItemResponse, ItemsUpdateItemError, LoginLoginAccessTokenData, LoginLoginAccessTokenResponse, LoginLoginAccessTokenError, LoginTestTokenData, LoginTestTokenResponse, LoginRecoverPasswordData, LoginRecoverPasswordResponse, LoginRecoverPasswordError, LoginResetPasswordData, LoginResetPasswordResponse, LoginResetPasswordError, LoginRecoverPasswordHtmlContentData, LoginRecoverPasswordHtmlContentResponse, LoginRecoverPasswordHtmlContentError, UtilsTestEmailData, UtilsTestEmailResponse, UtilsTestEmailError, UtilsHealthCheckData, UtilsHealthCheckResponse, UsersReadUsersData, UsersReadUsersResponse, UsersReadUsersError, UsersCreateUserData, UsersCreateUserResponse, UsersCreateUserError, UsersDeleteUserMeData, UsersDeleteUserMeResponse, UsersReadUserMeData, UsersReadUserMeResponse, UsersUpdateUserMeData, UsersUpdateUserMeResponse, UsersUpdateUserMeError, UsersUpdatePasswordMeData, UsersUpdatePasswordMeResponse, UsersUpdatePasswordMeError, UsersRegisterUserData, UsersRegisterUserResponse, UsersRegisterUserError, UsersDeleteUserData, UsersDeleteUserResponse, UsersDeleteUserError, UsersReadUserByIdData, UsersReadUserByIdResponse, UsersReadUserByIdError, UsersUpdateUserData, UsersUpdateUserResponse, UsersUpdateUserError } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class ItemsService {
    /**
     * Read Items
     * Retrieve items.
     */
    public static readItems<ThrowOnError extends boolean = true>(options?: Options<ItemsReadItemsData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<ItemsReadItemsResponse, ItemsReadItemsError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/v1/items/',
            ...options
        });
    }
    
    /**
     * Create Item
     * Create new item.
     */
    public static createItem<ThrowOnError extends boolean = true>(options: Options<ItemsCreateItemData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<ItemsCreateItemResponse, ItemsCreateItemError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/v1/items/',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Delete Item
     * Delete an item.
     */
    public static deleteItem<ThrowOnError extends boolean = true>(options: Options<ItemsDeleteItemData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).delete<ItemsDeleteItemResponse, ItemsDeleteItemError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/v1/items/{id}',
            ...options
        });
    }
    
    /**
     * Read Item
     * Get item by ID.
     */
    public static readItem<ThrowOnError extends boolean = true>(options: Options<ItemsReadItemData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).get<ItemsReadItemResponse, ItemsReadItemError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/v1/items/{id}',
            ...options
        });
    }
    
    /**
     * Update Item
     * Update an item.
     */
    public static updateItem<ThrowOnError extends boolean = true>(options: Options<ItemsUpdateItemData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).put<ItemsUpdateItemResponse, ItemsUpdateItemError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/v1/items/{id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
}

export class LoginService {
    /**
     * Login Access Token
     * OAuth2 compatible token login, get an access token for future requests
     */
    public static loginAccessToken<ThrowOnError extends boolean = true>(options: Options<LoginLoginAccessTokenData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<LoginLoginAccessTokenResponse, LoginLoginAccessTokenError, ThrowOnError>({
            ...urlSearchParamsBodySerializer,
            url: '/api/v1/login/access-token',
            ...options,
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded',
                ...options?.headers
            }
        });
    }
    
    /**
     * Test Token
     * Test access token
     */
    public static testToken<ThrowOnError extends boolean = true>(options?: Options<LoginTestTokenData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).post<LoginTestTokenResponse, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/v1/login/test-token',
            ...options
        });
    }
    
    /**
     * Recover Password
     * Password Recovery
     */
    public static recoverPassword<ThrowOnError extends boolean = true>(options: Options<LoginRecoverPasswordData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<LoginRecoverPasswordResponse, LoginRecoverPasswordError, ThrowOnError>({
            url: '/api/v1/password-recovery/{email}',
            ...options
        });
    }
    
    /**
     * Reset Password
     * Reset password
     */
    public static resetPassword<ThrowOnError extends boolean = true>(options: Options<LoginResetPasswordData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<LoginResetPasswordResponse, LoginResetPasswordError, ThrowOnError>({
            url: '/api/v1/reset-password/',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Recover Password Html Content
     * HTML Content for Password Recovery
     */
    public static recoverPasswordHtmlContent<ThrowOnError extends boolean = true>(options: Options<LoginRecoverPasswordHtmlContentData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<LoginRecoverPasswordHtmlContentResponse, LoginRecoverPasswordHtmlContentError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/v1/password-recovery-html-content/{email}',
            ...options
        });
    }
    
}

export class UtilsService {
    /**
     * Test Email
     * Test emails.
     */
    public static testEmail<ThrowOnError extends boolean = true>(options: Options<UtilsTestEmailData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<UtilsTestEmailResponse, UtilsTestEmailError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/v1/utils/test-email/',
            ...options
        });
    }
    
    /**
     * Health Check
     */
    public static healthCheck<ThrowOnError extends boolean = true>(options?: Options<UtilsHealthCheckData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<UtilsHealthCheckResponse, unknown, ThrowOnError>({
            url: '/api/v1/utils/health-check/',
            ...options
        });
    }
    
}

export class UsersService {
    /**
     * Read Users
     * Retrieve users.
     */
    public static readUsers<ThrowOnError extends boolean = true>(options?: Options<UsersReadUsersData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<UsersReadUsersResponse, UsersReadUsersError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/v1/users/',
            ...options
        });
    }
    
    /**
     * Create User
     * Create new user.
     */
    public static createUser<ThrowOnError extends boolean = true>(options: Options<UsersCreateUserData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<UsersCreateUserResponse, UsersCreateUserError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/v1/users/',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Delete User Me
     * Delete own user.
     */
    public static deleteUserMe<ThrowOnError extends boolean = true>(options?: Options<UsersDeleteUserMeData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).delete<UsersDeleteUserMeResponse, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/v1/users/me',
            ...options
        });
    }
    
    /**
     * Read User Me
     * Get current user.
     */
    public static readUserMe<ThrowOnError extends boolean = true>(options?: Options<UsersReadUserMeData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<UsersReadUserMeResponse, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/v1/users/me',
            ...options
        });
    }
    
    /**
     * Update User Me
     * Update own user.
     */
    public static updateUserMe<ThrowOnError extends boolean = true>(options: Options<UsersUpdateUserMeData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).patch<UsersUpdateUserMeResponse, UsersUpdateUserMeError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/v1/users/me',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Update Password Me
     * Update own password.
     */
    public static updatePasswordMe<ThrowOnError extends boolean = true>(options: Options<UsersUpdatePasswordMeData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).patch<UsersUpdatePasswordMeResponse, UsersUpdatePasswordMeError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/v1/users/me/password',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Register User
     * Create new user without the need to be logged in.
     */
    public static registerUser<ThrowOnError extends boolean = true>(options: Options<UsersRegisterUserData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<UsersRegisterUserResponse, UsersRegisterUserError, ThrowOnError>({
            url: '/api/v1/users/signup',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Delete User
     * Delete a user.
     */
    public static deleteUser<ThrowOnError extends boolean = true>(options: Options<UsersDeleteUserData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).delete<UsersDeleteUserResponse, UsersDeleteUserError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/v1/users/{user_id}',
            ...options
        });
    }
    
    /**
     * Read User By Id
     * Get a specific user by id.
     */
    public static readUserById<ThrowOnError extends boolean = true>(options: Options<UsersReadUserByIdData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).get<UsersReadUserByIdResponse, UsersReadUserByIdError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/v1/users/{user_id}',
            ...options
        });
    }
    
    /**
     * Update User
     * Update a user.
     */
    public static updateUser<ThrowOnError extends boolean = true>(options: Options<UsersUpdateUserData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).patch<UsersUpdateUserResponse, UsersUpdateUserError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/v1/users/{user_id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
}