name: Lint Frontend

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'
    - name: Install dependencies
      run: npm install
      working-directory: frontend
    - name: Run BiomeJS linter
      run: npx biome lint
      working-directory: frontend
